services:
   node:
      container_name: NestJS Application
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3001:3001'
      depends_on:
         - redis
         - kafka
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
      networks:
         - app-network

   redis:
      image: 'redis'
      container_name: Redis
      ports:
         - '6379:6379'
      networks:
         - app-network

   kafka:
      image: 'apache/kafka:latest'
      container_name: Apache Kafka
      ports:
         - '9092:9092'
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
