services:
   node:
      container_name: NestJS Application
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3001:3001'
      volumes:
         - .:/apps
      depends_on:
         - redis
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
      networks:
         - app-network

   redis:
      image: 'redis'
      container_name: Redis
      volumes:
         - /redis:/redis
      ports:
         - '6379:6379'
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
