packages:
  - packages/*
  - .

allowBuilds:
  '@automock/adapters.nestjs': true
  '@compodoc/compodoc': true
  '@nestjs/core': true
  '@sentry/cli': true
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/profiling-node': true
  '@swc/core': true
  bcrypt: true
  msgpackr-extract: true
  nestjs-pino: set this to true or false

onlyBuiltDependencies:
  - '@compodoc/compodoc'
