# mongod.conf

# * $BASE_DIR là folder cài đặt MongoDB replica set. Ex: C:/Program Files/MongoDB/Server/8.0

# * $HOST là địa chỉ host của MongoDB cần expose ra bên ngoài. Ex: 0.0.0.0

# * $PORT là cổng của 1 node trong replica set. Ex: 27017,27018,27019


# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: $BASE_DIR/$PORT/data
  wiredTiger:
    engineConfig:
      cacheSizeGB: 6

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: $BASE_DIR/$PORT/log/mongod.log

# network interfaces
net:
  port: $PORT
  bindIp: $HOST

#processManagement:

#security:

#operationProfiling:

replication:
  replSetName: "rs0"
  oplogSizeMB: 10240
#sharding:

## Enterprise-Only Options:

#auditLog:
