import { DefaultJobOptions } from 'bullmq'

export const BULK_WRITE_INBOUND_EPCS_QUEUE = 'BULK_WRITE_INBOUND_EPCS_QUEUE'
export const BULK_WRITE_OUTBOUND_EPCS_QUEUE = 'BULK_WRITE_OUTBOUND_EPCS_QUEUE'
export const IMPORT_INOUTBOUND_EPCS_QUEUE = 'IMPORT_INOUTBOUND_EPCS_QUEUE'
export const COMMIT_UPSERT_EPC_MATCH_QUEUE = 'COMMIT_UPSERT_EPC_MATCH_QUEUE'
export const COMMIT_EXCHANGE_MO_QUEUE = 'COMMIT_EXCHANGE_MO_QUEUE'
export const COMMIT_STOCK_BALANCES_QUEUE = 'COMMIT_STOCK_BALANCES_QUEUE'
export const COMMIT_STOCK_OUT_QUEUE = 'COMMIT_STOCK_OUT_QUEUE'
export const ROLLBACK_INBOUND_TX_QUEUE = 'ROLLBACK_INBOUND_TX_QUEUE'

export const FINISHED_GOODS_JOB_OPTIONS: DefaultJobOptions = {
	attempts: 10,
	removeOnComplete: { count: 10 },
	removeOnFail: { count: 100 },
	backoff: { type: 'fixed', delay: 3000 }
}
