name: Deploy app to Windows Server (Self-hosted)

on:
   push:
      branches:
         - develop

jobs:
   sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: SonarCloud Scan
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   deploy-server-19:
      name: Deploy to server 0.19
      runs-on: [self-hosted, 'Server-19']
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0
              clean: false

         - name: Load environment variables
           shell: bash
           run: echo "${{ secrets.ENV_VARIABLE_SVR19 }}" > .env

         - name: Initialize Sentry CLI
           shell: bash
           run: |
              echo "[auth]" > .sentryclirc
              echo "token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .sentryclirc

         - name: Install dependencies
           shell: bash
           run: pnpm install

         - name: Build Nest application
           shell: bash
           run: pnpm build

         - name: Restart and save PM2 process
           shell: bash
           run: |
              pm2 restart ecosystem.config.js --update-env
              pm2 save

   deploy-server-5251:
      name: Deploy to server 5.251
      runs-on: [self-hosted, 'Server-5251']
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0
              clean: false

         - name: Load environment variables
           shell: bash
           run: echo "${{ secrets.ENV_VARIABLE_SVR5251 }}" > .env

         - name: Initialize Sentry CLI
           shell: bash
           run: |
              echo "[auth]" > .sentryclirc
              echo "token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .sentryclirc

         - name: Install dependencies
           shell: bash
           run: pnpm install

         - name: Build Nest application
           shell: bash
           run: pnpm build

         - name: Restart and save PM2 process
           shell: bash
           run: |
              pm2 restart ecosystem.config.js --update-env
              pm2 save
